[package]
name = "rust3ds-template"
version = "0.1.0"
description = "Nintendo 3DS project template"

[dependencies.ctru-rs]
git = "https://github.com/FenrirWolf/ctru-rs"

[dependencies.alloc_system3ds]
git = "https://github.com/FenrirWolf/alloc_system3ds"

[profile.dev]
lto = true

[profile.release]
lto = true
