[package]
description = "Nintendo 3DS project template"
name = "rust3ds-template"
version = "0.1.0"

[dependencies.alloc_system3ds]
git = "https://github.com/Furyhunter/alloc_system3ds"

[dependencies.ctru-rs]
path = "../ctru-rs"

[profile.dev]
lto = true

[profile.release]
lto = true
